server.port=8080

# ===============================
# 1. DATABASE (Render Cloud Connection)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d4jvtm2li9vc73de3k10-a.oregon-postgres.render.com/pdfly
spring.datasource.username=pdfly_user
spring.datasource.password=9QrQSvtF5lUhqCJDiDGdLPZj7ekoVB96

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# 2. EMAIL (Final Configuration - Switching to Port 465)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=aadityabasisthdev@gmail.com
spring.mail.password=wagoayjbdawrbhnt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.ssl.enable=true

# ===============================
# 3. SECURITY (JWT)
# ===============================
jwt.secret=315564dee2502afab40dcfb92fe1a77942d4783be45e782c82079b266d11d36dea43c974c8479a706cd4c35c1300f1ef3fbbee515f671c48e320d82b6f7eaf2d
jwt.expiration=86400000

# ===============================
# 4. FILE LIMITS
# ===============================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB